# Generated by Django 4.1.2 on 2022-10-19 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0002_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='miesiac_urodzenia',
        ),
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
