# Generated by Django 4.1.2 on 2022-10-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0005_alter_osoba_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('kraj', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='osoba',
            name='druzyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab3.druzyna'),
        ),
    ]
